### PR TITLE
Add a new language, Lao 🇱🇦

### PR DESCRIPTION
**Pull request by TheBrown**
My experience was as a translator for the Mozilla project (which I am still doing).
You can download the Mozilla Firefox Browser Nightly Version (select lo lang).
ref: [`contributors`](https://pontoon.mozilla.org/lo/contributors/)

I hope this will be a chance to help grow the ReactJS community in Laos.

### CODE REVIEW

**Comment by gaearon** [comment]
Let's see if this works! If this doesn't work, I'll check what's up with the permission synchronization script.

**Comment by gaearon** [comment]
The permission thing on this PR is unrelated, but I'll look into what's going on with the permission sync today.

**Comment by TheBrown** [comment]
It's still not creating a new repository for lo. Have you found the solution @gaearon ?

**Comment by gaearon** [comment]
I’m working on overhauling how everything works here. Hang tight.

**Comment by gaearon** [comment]
Done: https://github.com/reactjs/lo.react.dev/issues/1

**Comment by TheBrown** [comment]
Thank you so much @gaearon

**Pull request merged**
