### PR TITLE
Telugu translation te.json

### PR DESCRIPTION
**Pull request by g-savitha**
I'ma a native Telugu speaker. Working on react since 2016. Telugu is one of the most popular languages in India. I have a good experience in maintaining and contributing to the open-source repos.  I also have good experience in internationalisation.

### CODE REVIEW

**Comment by g-savitha** [comment]
I have no experience in translating official websites like this one, but I’m good at i18n

**Comment by vamsikrishnareddybevara** [comment]
I am a native Telugu speaker and I have been using reactjs for 3 years. I would like to contribute.

**Comment by gsteja2307** [comment]
I am interested in contributing

**Review by gaearon — CHANGES_REQUESTED** [review]
As a part of fixing the permission sync process, we've changed how we track languages — please see https://github.com/reactjs/translations.react.dev/commit/63a10c4be3f7b10ffaf58fe144e2d5abca5dacc9. 
Could you please update this PR:

- Rebase on top of latest `main`, and add the language to `lang/langs.json` instead
- Include the list of maintainers into the PR comment body instead

Thank you, and sorry for the churn.

**Comment by g-savitha** [comment]
Sure. Will update it.

**Comment by g-savitha** [comment]
Hey @gaearon ,

Earlier I raised this PR directly from my mobile. I forked this repo today and made the changes you mentioned here https://github.com/reactjs/translations.react.dev/pull/289 . Can you please check this.  If this PR is irrelevant now, you can close it.

Thanks

**Comment by CarreraPHP** [comment]
@g-savitha , can you close this old PR.

**Pull request closed without merging**
