### PR TITLE
malayalam lang

### PR DESCRIPTION
**Pull request by adarshm07**
This is a new PR created as per the comment on the previous pr. Malayalam is a regional language in Kerala, India.

### CODE REVIEW

**Review by gaearon — CHANGES_REQUESTED** [review]
Thanks! Please find at least one more person who'd like to help maintain this translation, and ask them to comment on this PR for confirmation.

**Comment by asimkt** [comment]
I'm interested in joining forces. Can you add me as a maintainer @adarshm07 ?

**Comment by gaearon** [comment]
Sounds good, creating the repo now.

**Comment by asimkt** [comment]
Thank @gaearon

**Pull request merged**
