### PR TITLE
Add Belarusian language

### PR DESCRIPTION
**Pull request by zubialevich**
Hi! I would like to translate reactjs.org to belarusian language. This is an official language in Belarus.

### CODE REVIEW

**Comment by zubialevich** [comment]
Hi! Any details about this one? Am I missing some details I need to fulfil?

**Review by gaearon — CHANGES_REQUESTED** [review]
Hi! Thank you for the request.

Can you please find at least one other person who'd like to commit to maintaining this translation, and have them comment on this PR as a confirmation?

Thanks!

**Comment by belarusaed** [comment]
Hi, I can help with this translation

**Comment by gaearon** [comment]
Sounds good, creating a translation owned by @zubialevich and @belarusaed.

**Pull request merged**
