### PR TITLE
Add bengali language

### PR DESCRIPTION
**Pull request by ahnafyy**
I have over 6 years of react experience as well haven take over 12 years of learning the bengali language in an academic setting.

### CODE REVIEW

**Comment by ahnafyy** [comment]
@gaearon can I please get a review?

**Comment by shakib609** [comment]
Hello @ahnafyy 

Great that you took the initiative to add Bengali translations for the new website. me and @nutboltu have been maintaining the previous react translations. Would love to start translating the new version react docs.

Can you kindly add me as well to the maintainers list?

You can check my previous translation PRs [here](https://github.com/stale-reactjs-org-translations/bn.reactjs.org/pulls?q=is%3Aclosed+is%3Apr+author%3Ashakib609+).

Also, another thing I noticed in the json file is the language code.
It should be `bn` (ISO 639-1 Code).
The previous site was also located at `https://bn.reactjs.org` as well.

Cheers. Looking forward to starting the new translations.

**Comment by moshfiqrony** [comment]
There is a [PR](https://github.com/reactjs/translations.react.dev/pull/266) already open for Bengali. Let's everyone collaborate there. Let us know in the PR if you are interested.

Best,
Rony

**Comment by ahnafyy** [comment]
Closing this out @shakib609 and @moshfiqrony  and joining the other PR! 

Thanks!

**Pull request closed without merging**
