### PR TITLE
Add Tamil Language

### PR DESCRIPTION
**Pull request by CarreraPHP**
@gaearon,

As discussed with you earlier, I have formed a small team of passionate react developers who can speak, read & write in Tamil fluently. We don't have translation or tech writing experience before. 

But, we do have the necessity to have the documentation in our Language and it would greatly help us in the training process.

Regards,
Yogesh Surendran

### CODE REVIEW

**Comment by CarreraPHP** [comment]
@tesseralis is there anything left to do from our side?

**Review by gaearon — CHANGES_REQUESTED** [review]
As a part of fixing the permission sync process, we've changed how we track languages — please see https://github.com/reactjs/translations.react.dev/commit/63a10c4be3f7b10ffaf58fe144e2d5abca5dacc9. 
Could you please update this PR:

- Rebase on top of latest `main`, and add the language to `lang/langs.json` instead
- Include the list of maintainers into the PR comment body instead

Thank you, and sorry for the churn.

**Comment by CarreraPHP** [comment]
@gaearon , have done the changes needed.

**Review by CarreraPHP — COMMENTED** [review]
Have removed the newly added ta.json file and updated the langs.json file

**Pull request merged**
